spring.application.name=hr-platform

# H2 baza
spring.datasource.url=jdbc:h2:mem:hrplatform
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 konzola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicijalizacija podataka
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true