-- Kategorije
INSERT INTO CATEGORIES (NAME) VALUES ('Programming');
INSERT INTO CATEGORIES (NAME) VALUES ('Language');
INSERT INTO CATEGORIES (NAME) VALUES ('Design');

-- Vestine
INSERT INTO SKILLS (NAME, DESCRIPTION, CATEGORY_ID) VALUES ('Java', 'Object oriented programming language', 1);
INSERT INTO SKILLS (NAME, DESCRIPTION, CATEGORY_ID) VALUES ('C#', 'Microsoft programming language', 1);
INSERT INTO SKILLS (NAME, DESCRIPTION, CATEGORY_ID) VALUES ('English', 'Business English', 2);
INSERT INTO SKILLS (NAME, DESCRIPTION, CATEGORY_ID) VALUES ('German', 'German language', 2);
INSERT INTO SKILLS (NAME, DESCRIPTION, CATEGORY_ID) VALUES ('Database Design', 'SQL and NoSQL databases', 3);

-- Kandidati
INSERT INTO CANDIDATES (FIRST_NAME, LAST_NAME, FULL_NAME, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL) 
VALUES ('Ana', 'Jovic', 'Ana Jovic', '1995-03-15', '0641234567', 'ana@gmail.com');
INSERT INTO CANDIDATES (FIRST_NAME, LAST_NAME, FULL_NAME, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL) 
VALUES ('Marko', 'Petrovic', 'Marko Petrovic', '1990-07-22', '0659876543', 'marko@gmail.com');
INSERT INTO CANDIDATES (FIRST_NAME, LAST_NAME, FULL_NAME, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL) 
VALUES ('Petar', 'Zivojinovic', 'Petar Zivojinovic', '1988-11-05', '0671112233', 'petar@gmail.com');

-- Vestine kandidata
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (1, 3);
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (2, 2);
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (2, 3);
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (3, 1);
INSERT INTO CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID) VALUES (3, 5);